Repository 2unbini/pple, pull requests merged in 2021-12, with the labels that each got.

#8 [feat] Created Project List and Add, Edit Sheet UI #6
  i-scheduler/i-scheduler/AddSheet.swift
  i-scheduler/i-scheduler/EditSheet.swift
  i-scheduler/i-scheduler/ProjectGrid.swift
  i-scheduler/i-scheduler/ProjectList.swift
  i-scheduler/i-scheduler/TopBar.swift
Labels: enhancement

#13 [feat] Created ProjectCalendarView #9
  i-scheduler/i-scheduler/ProjectCalendarView.swift
Labels: enhancement

#17 [feat] Created Popup, DailyTaskList, DailyTaskRowView, TaskDetailView #10
  i-scheduler/i-scheduler/DailyTaskList.swift
  i-scheduler/i-scheduler/DailyTaskRowView.swift
  i-scheduler/i-scheduler/Popup.swift
  i-scheduler/i-scheduler/TaskDetailView.swift
Labels: enhancement

#28 [feat] Fetch data in Project List #25
  i-scheduler/i-scheduler/ProjectList.swift
Labels: enhancement

#31 [feat] integrated core data into PopUpTaskList, TaskList, TaskRowView, TaskDetailView #23
  i-scheduler/i-scheduler.xcodeproj/project.pbxproj
  i-scheduler/i-scheduler/CheckBox.swift
  i-scheduler/i-scheduler/DailyTaskRowView.swift
  i-scheduler/i-scheduler/PopUpTaskList.swift
  i-scheduler/i-scheduler/Popup.swift
  i-scheduler/i-scheduler/TaskDetailView.swift
  i-scheduler/i-scheduler/TaskList.swift
  i-scheduler/i-scheduler/TaskRowView.swift
  i-scheduler/i-scheduler/UtilityExtensions.swift
Labels: enhancement

#33 [feat] refactored PoupUpTaskList #32
  i-scheduler/i-scheduler.xcodeproj/project.pbxproj
  i-scheduler/i-scheduler/Cardify.swift
  i-scheduler/i-scheduler/PopUpTaskList.swift
  i-scheduler/i-scheduler/UtilityExtensions.swift
Labels: refactor

#36 [feat] Modify Data Type to normalize .sheet #35
  i-scheduler/i-scheduler/ProjectList.swift
Labels: enhancement

#34 [feat] Add Edit and Save Function #26
  i-scheduler/i-scheduler.xcodeproj/project.pbxproj
  i-scheduler/i-scheduler/AddSheet.swift
  i-scheduler/i-scheduler/EditSheet.swift
  i-scheduler/i-scheduler/Enums.swift
  i-scheduler/i-scheduler/TemporaryModel.swift
  i-scheduler/i-scheduler/ToolBar.swift
  i-scheduler/i-scheduler/TopBar.swift
Labels: enhancement

#39 [feat] maxgrid #24
  i-scheduler/i-scheduler/ProjectCalendarView.swift
Labels: enhancement

#54 [feat] Fixed Screen Separation in ProjectList #43
  i-scheduler/i-scheduler/ProjectList.swift
Labels: bug

#53 [feat] refactored views with projectId #48
  i-scheduler/i-scheduler/ProjectCalendarView.swift
  i-scheduler/i-scheduler/TaskDetailView.swift
  i-scheduler/i-scheduler/TaskList.swift
  i-scheduler/i-scheduler/TaskRowView.swift
Labels: refactor

#55 [feat] refactored modifiedForPredicates method #47
  i-scheduler/i-scheduler/TaskList.swift
  i-scheduler/i-scheduler/UtilityExtensions.swift
Labels: refactor

#57 [feat] Passing Data including measured size #56
  i-scheduler/i-scheduler/ProjectCalendarView.swift
  i-scheduler/i-scheduler/TaskList.swift
Labels: enhancement

#58 [feat] Separate Edit/AddSheet and ToolBar #44
  i-scheduler/i-scheduler/AddSheet.swift
  i-scheduler/i-scheduler/EditSheet.swift
  i-scheduler/i-scheduler/Enums.swift
  i-scheduler/i-scheduler/ProjectList.swift
  i-scheduler/i-scheduler/TemporaryModel.swift
  i-scheduler/i-scheduler/ToolBar.swift
Labels: enhancement

#61 [feat]fixing_bug(showing_day)_in_ProjectCalendarView #60
  i-scheduler/i-scheduler/ProjectCalendarView.swift
Labels: bug

#64 [feat] Enhance Project List #45
  i-scheduler/i-scheduler/Enums.swift
  i-scheduler/i-scheduler/ProjectList.swift
  i-scheduler/i-scheduler/ToolBar.swift
Labels: enhancement

#65 [feat] Sheet Binding with Views #44
  i-scheduler/i-scheduler.xcodeproj/project.pbxproj
  i-scheduler/i-scheduler/ProjectAddSheet.swift
  i-scheduler/i-scheduler/ProjectCalendarView.swift
  i-scheduler/i-scheduler/ProjectEditSheet.swift
  i-scheduler/i-scheduler/ProjectToolBar.swift
  i-scheduler/i-scheduler/TaskAddSheet.swift
  i-scheduler/i-scheduler/TaskDetailView.swift
  i-scheduler/i-scheduler/TaskEditSheet.swift
  i-scheduler/i-scheduler/TaskList.swift
  i-scheduler/i-scheduler/TaskToolBar.swift
Labels: enhancement

#75 [feat] Fix Task Add Sheet and Modified TempData #66
  i-scheduler/i-scheduler/ProjectAddSheet.swift
  i-scheduler/i-scheduler/ProjectEditSheet.swift
  i-scheduler/i-scheduler/TaskAddSheet.swift
  i-scheduler/i-scheduler/TaskEditSheet.swift
  i-scheduler/i-scheduler/TemporaryModel.swift
Labels: bug, enhancement

#70 [feat] fixed popup bug in real device #52 #50 #49
  i-scheduler/i-scheduler.xcodeproj/project.pbxproj
  i-scheduler/i-scheduler/Cardify.swift
  i-scheduler/i-scheduler/PopupView.swift
  i-scheduler/i-scheduler/ProjectCalendarView.swift
  i-scheduler/i-scheduler/TaskList.swift
  i-scheduler/i-scheduler/UtilityExtensions.swift
Labels: bug

#73 [feat] shows CarouselView of TaskLists in Popup #37
  i-scheduler/i-scheduler.xcodeproj/project.pbxproj
  i-scheduler/i-scheduler/ACarousel/ACarousel.swift
  i-scheduler/i-scheduler/ACarousel/ACarouselAutoScroll.swift
  i-scheduler/i-scheduler/ACarousel/ACarouselViewModel.swift
  i-scheduler/i-scheduler/ACarousel/AppLifeCycleModifier.swift
  i-scheduler/i-scheduler/ACarousel/View+ReceiveTimer.swift
  i-scheduler/i-scheduler/ProjectCalendarView.swift
Labels: enhancement

#79 [feat] Fix EditMode Separation in NavigationLink #43
  i-scheduler/i-scheduler/ProjectList.swift
Labels: enhancement

#77 [feat] changed popup animation to opacity #72
  i-scheduler/i-scheduler/PopupView.swift
  i-scheduler/i-scheduler/ProjectCalendarView.swift
Labels: enhancement
